### ISSUE TITLE
Naming of Breadcrumbs component seems wrong

### ISSUE THREAD

**Issue by Franklin89** [farmerconnect/farmerconnect-ui#17]
The current storybook contains a component called `Breadcrumbs` which is not a breadcrumb but more a wizard step component.

[Linkt to storybook](https://ui.farmerconnect.com/?path=/story/breadcrumbs--default)

**Comment by gateixeira** [comment]
@Franklin89 I'm not sure if I agree. I get that HTML breadcrumb is more to indicate location in a hierarchy of pages and that in our case we do use it a bit differently but it still can be used as a breadcrumb. The idea for the components is to be deep to the most generic one we can relate to

**Comment by gateixeira** [comment]
As agreed, this will be a breadcrumb:
![image](https://user-images.githubusercontent.com/4645845/120323689-0bbaf300-c2e6-11eb-806e-8ff42f87a3d9.png)
