### ISSUE TITLE
Filter Select unable to delete the selected text and unable to delete first character

### ISSUE THREAD

**Issue by Franklin89** [farmerconnect/farmerconnect-ui#54]
Inside of a Filter Select component, I can not delete the complete text that has been highlighted. It is also not possible to delete the first character with backspace.

**Comment by 328d95** [comment]
@Franklin89 Seems like this is working now!


https://user-images.githubusercontent.com/5643276/131833085-db220a6e-a4c9-467a-9288-1e9feb8b5ac4.mov
